### ISSUE TITLE
save layout.

### ISSUE THREAD

**Issue by ctf0** [Zeeker/sublime-SessionManager#1]
can u plz also add the ability to save the layers group-layout ?

**Comment by Zeeker** [comment]
You mean these?

![](https://cloud.githubusercontent.com/assets/2647626/6651789/fcbeee50-ca54-11e4-8dae-b046e5fa4475.png)

**Comment by ctf0** [comment]
yeap

**Comment by Bystroushaak** [comment]
I would also use this feature.
